ns: logging

es:
  name: elasticsearch
  port1: 9200
  port2: 9300
  portname1: rest
  portname2: inter-node
  ssname: es-cluster
  replicas: 3
  image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
  volume:
    name: data
    mountPath: /usr/share/elasticsearch/data
  env:
    name1: discovery.seed_hosts
    value1: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
    name2: cluster.initial_master_nodes
    value2: "es-cluster-0,es-cluster-1,es-cluster-2"
    name3: ES_JAVA_OPTS
    value3: "-Xms512m -Xmx512m"

fluentd:
  name: fluentd
  image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
  terminationSeconds: 30
  volumeMounts:
    name1: varlog
    mountPath1: /var/log
    name2: varlibdockercontainers
    mountPath2: /var/lib/docker/containers

kibana:
  name: kibana
  port: 5601
  env:
    name: ELASTICSEARCH_URL
    value: http://elasticsearch:9200

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 200Mi
    storage: 100Gi