---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.es.name }}
  namespace: {{ .Values.ns }}
  labels:
    app: {{ .Values.es.name }}
spec:
  selector:
    app: {{ .Values.es.name }}
  clusterIP: None
  ports:
    - port: {{ .Values.es.port1 }}
      name: {{ .Values.es.portname1 }}
    - port: {{ .Values.es.port2 }}
      name: {{ .Values.es.portname2 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.es.ssname }}
  namespace: {{ .Values.ns }}
spec:
  serviceName: {{ .Values.es.name }}
  replicas: {{ .Values.es.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.es.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.es.name }}
    spec:
      containers:
      - name: {{ .Values.es.name }}
        image: {{ .Values.es.image }}
        resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
        ports:
        - containerPort: {{ .Values.es.port1 }}
          name: {{ .Values.es.portname1 }}
          protocol: TCP
        - containerPort: {{ .Values.es.port2 }}
          name: {{ .Values.es.portname2 }}
          protocol: TCP
        volumeMounts:
        - name: {{ .Values.es.volume.name }}
          mountPath: {{ .Values.es.volume.mountPath }}
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: {{ .Values.es.env.name1 }}
            value: {{ .Values.es.env.value1 | quote }}
          - name: {{ .Values.es.env.name2 }}
            value: {{ .Values.es.env.value2 | quote }}
          - name: {{ .Values.es.env.name3 }}
            value: {{ .Values.es.env.value3 | quote }}
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: {{ .Values.es.volume.name }}
          mountPath: {{ .Values.es.volume.mountPath }}
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ .Values.es.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp2
      resources:
        requests:
          storage: {{ .Values.resources.requests.storage }}