---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fluentd.name }}
  namespace: {{ .Values.ns }}
  labels:
    app: {{ .Values.fluentd.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.fluentd.name }}
  labels:
    app: {{ .Values.fluentd.name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.fluentd.name }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.fluentd.name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.fluentd.name }}
  namespace: {{ .Values.ns }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.fluentd.name }}
  namespace: {{ .Values.ns }}
  labels:
    app: {{ .Values.fluentd.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.fluentd.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.fluentd.name }}
    spec:
      serviceAccount: {{ .Values.fluentd.name }}
      serviceAccountName: {{ .Values.fluentd.name }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: {{ .Values.fluentd.name }}
        image: {{ .Values.fluentd.image }}
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch.logging.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - name: {{ .Values.fluentd.volumeMounts.name1 }}
          mountPath: {{ .Values.fluentd.volumeMounts.mountPath1 }}
        - name: {{ .Values.fluentd.volumeMounts.name2 }}
          mountPath: {{ .Values.fluentd.volumeMounts.mountPath2 }}
          readOnly: true
      terminationGracePeriodSeconds: {{ .Values.fluentd.terminationSeconds }}
      volumes:
      - name: {{ .Values.fluentd.volumeMounts.name1 }}
        hostPath:
          path: {{ .Values.fluentd.volumeMounts.mountPath1 }}
      - name: {{ .Values.fluentd.volumeMounts.name2 }}
        hostPath:
          path: {{ .Values.fluentd.volumeMounts.mountPath2 }}