---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.name }}
  namespace: {{ .Values.ns }}
  labels:
    app: {{ .Values.kibana.name }}
spec:
  ports:
  - port: {{ .Values.kibana.port }}
  selector:
    app: {{ .Values.kibana.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kibana.name }}
  namespace: {{ .Values.ns }}
  labels:
    app: {{ .Values.kibana.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kibana.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kibana.name }}
    spec:
      containers:
      - name: {{ .Values.kibana.name }}
        image: docker.elastic.co/kibana/kibana:7.2.0
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
        env:
          - name: {{ .Values.kibana.env.name }}
            value: {{ .Values.kibana.env.value }}
        ports:
        - containerPort: {{ .Values.kibana.port }}